### PR TITLE
REFACTOR: Busting up the SearchModule monolith

### PR DESCRIPTION
**Pull request by smcpeck**
I've started on a refactor of the SearchModule stuff.  Just getting this PR created early so you can add some commentary along the way.  It won't be ready for merge consideration for some time yet.

The plan is:

1. Move existing code as-is into separate modules just to get things working with the new classes in place and organize the code properly.
2. Refactor each individual new module to clean up some of the code.  There are single functions that are pretty beastly as it stands right now.

### CODE REVIEW

**Comment by tidusjar** [comment]
I like where you are going with this!

**Comment by smcpeck** [comment]
This is mostly ready, I think, from a "step 1" perspective.

GitHub is pissed about the weird merge, it seems.  Any insight on that?

**Comment by smcpeck** [comment]
The initial refactor to split the classes up here is complete and I believe that everything is functional.  Do you want to run this through some basic testing & merge this into `dev` now just to take things one step at a time?  I can continue the refactoring while people exercise things a bit in the dev branch.

**Comment by tidusjar** [comment]
OK yes that's fine, i'll do some testing tonight.

I really appreciate the effort you have been putting in the past few days!

**Comment by smcpeck** [comment]
No worries -- It's been fun.  This is the first open source stuff I've done.

**Comment by tidusjar** [comment]
Glad you been enjoying it!

Just to let you know, i'm not going to merge this one in until I have pushed out a new release. Need to get things fixed up and ready and don't want to introduce many more changes. So once i've released i'll then merge this in :)

**Comment by smcpeck** [comment]
Just wanted to chime in here.  I'll be back on this when I get time...

**Comment by tidusjar** [comment]
That's cool, Like I mentioned, I don't want to merge this in until we have a stable release go out :)

**Comment by SuperPotatoMen** [comment]
@tidusjar  do you have time to look at this one?

**Pull request closed without merging**
