### PR TITLE
Quick fix for email false positive message. ISSUE: #1286

### PR DESCRIPTION
**Pull request by dhruvb14**
Also VS2017 without Update 1 complains about every cshtml file until updated. Just a FYI incase you updated and see the issue.

### CODE REVIEW

**Comment by tidusjar** [comment]
Ah I see what you mean now.

The `Send` property is true when there are movie items or tv items. So if it's false and there's a test email then it will be empty. But I guess we should still send it.

For test emails that have no content perhaps we should `Take(10)` just to get content in for movies and shows?

**Comment by dhruvb14** [comment]
I guess we could take(10) but then if there was some issue we would not know since the test email and normal email would have different code paths.

**Comment by tidusjar** [comment]
Very true.

Is this ready to be merged in? 😄

**Comment by dhruvb14** [comment]
Yes merge ready if you approve :-)

**Pull request merged**
