### PR TITLE
Fixing incorrect filter translation targets

### PR DESCRIPTION
**Pull request by jonocairns**
image

Current schema:

```
"Requests": {
    ...
    "Filter":"Filter",
  },
  "Filter":{
    ...
    "ClearFilter":"Clear Filter",
  }
```

### CODE REVIEW

**Comment by tidusjar** [comment]
Thanks!

Can this be done in the other translation files too?

**Comment by jonocairns** [comment]
@tidusjar It's just the reference to the translation target so it should fix all translations for `Requests.ClearFilter` and `Filter.Filter` (I think!)

**Comment by tidusjar** [comment]
Sorry I meant the other translation files. Crowdin will just recognise them as new translations and we will loose the translated values.

**Comment by jonocairns** [comment]
Sorry, I'm still getting familiar with the setup. I don't think I follow :(

**Comment by tidusjar** [comment]
That's fine!

So in the folder where the translations are, there are other ones. E.g. de.json we need to make the same changes in those files

**Comment by jonocairns** [comment]
Ah, these are references to already existing translations. I've double checked the json files and they're all there.

**Comment by tidusjar** [comment]
@jonocairns I know they are all there, but since you modified the "master" which is the `en` file then you also need to make the same changes in the other translations files.

**Comment by jonocairns** [comment]
I haven't edited the en.json file in this PR

**Comment by tidusjar** [comment]
Sorry i'm following. Can you please change the target branch to DotNetCore

**Pull request merged**
