### PR TITLE
Rewritten the whole newsletter template.

### PR DESCRIPTION
**Pull request by d1slact0r**
I have tested it on gmail.com and android 8 gmail app. Still needs some work for the iOS app but really close ! (https://github.com/tidusjar/Ombi/issues/2431)

### CODE REVIEW

**Comment by diedrichg** [comment]
Looks GREAT on Android 9, Gmail app 8.11.4.22168! Thank you for all your hard work!

**Comment by d1slact0r** [comment]
Not sure on how to build ombi (since the NewsletterTemplate.html was easy to pull without building I was getting away with not building it) but now that I updated HtmlTemplateGenerator.cs aswell, how can I test that ? (without building preferabel)

**Comment by tidusjar** [comment]
Ohhh docker... In that case I have no idea how to do it. Can you not just run the application outside of docker to test it?

**Comment by d1slact0r** [comment]
Not really at this point since it will cost time to setup again which I do not have, I currently just edit on my tablet/phone and then do those simple commands in my break at work

**Comment by d1slact0r** [comment]
Got some great news! It is working on Iphones, Ipads and android and gmail and MacOS :) now just some finishing touches.

**Comment by tidusjar** [comment]
Excellent news! Great work on this so far!

**Comment by d1slact0r** [comment]
Ready for merge!

**Comment by diedrichg** [comment]
I'm running 3.0.4048 and all looks great on Android Gmail. I love that you didn't include the movie backgrounds! It makes for a much cleaner, easy to read, professional look.

**Comment by tidusjar** [comment]
@d1slact0r Do you mind posting screenshots of it now on a few different mail clients?

**Comment by d1slact0r** [comment]
Should be all like the screenshot above. I'm mobile today so cannot upload screenshots to GitHub. Maybe add it and so different people can test it ?

**Comment by d1slact0r** [comment]
No worries happy to help to this awesome project! Thank you for the app :) 
Looking forward to the end result.

**Comment by tidusjar** [comment]
@diedrichg did you get a chance to test this?

**Comment by diedrichg** [comment]
Yes, I'm running the latest as mentioned above and all looks great. @d1slact0r did a great job!

**Comment by tidusjar** [comment]
Merged! Thanks a lot for all the hard work

**Pull request merged**
