### PR TITLE
Add placeholders to search inputs

### PR DESCRIPTION
**Pull request by uzegonemad**
iOS doesn't support input autofocusing (or the jQuery `focus()` event) so when you open the search screen, there's no indicator for what happens next.

I tried clicking the magnifying glass to bring up a search box - this adds placeholders so the user knows where to tap.

Before:
<a href="https://user-images.githubusercontent.com/430255/27756842-d6855f24-5dc0-11e7-8dff-9836c9718cde.jpg" target="_blank">img_2915</a>

After:
<a href="https://user-images.githubusercontent.com/430255/27756844-dee07794-5dc0-11e7-85d9-40db1cedcfa3.jpg" target="_blank">img_2916</a>

### CODE REVIEW

**Comment by tidusjar** [comment]
Excellent idea.

**Comment by tidusjar** [comment]
Thanks a lot!

**Comment by uzegonemad** [comment]
Thanks! Should I create my PRs against the `EAP` branch moving forward?

**Comment by tidusjar** [comment]
I've already done it and its now available in the EAP

**Comment by uzegonemad** [comment]
Sorry for the confusion - I mean if I submit another pull request in the future, should it be to `master` or to `EAP`?

**Comment by tidusjar** [comment]
EAP :)

**Pull request merged**
