### PR TITLE
Add Gotify as notification provider

### PR DESCRIPTION
**Pull request by Aerion**
[Gotify](https://gotify.net/) is a self-hosted notification service. This PR adds Gotify as another provider for notifications.

* `ApplicationToken` is generated from Gotify and is used to identify the app (here Ombi).
* `Priority` defines the priority of the notification.

This has been tested on my instance of Ombi.

### CODE REVIEW

**Comment by Aerion** [comment]
The CI should pass when https://github.com/tidusjar/Ombi/pull/2898 is merged, do you prefer that I apply the patch in this PR too?

**Comment by tidusjar** [comment]
Wow nice. Looks like you've done quite a lot of work here! 

Do you mind posting some steps for me to test this? Just some basic ones? Since I've never heard of that provider before?

**Comment by Aerion** [comment]
> Do you mind posting some steps for me to test this? Just some basic ones? Since I've never heard of that provider before?

You can setup your own instance of Gotify just by following https://gotify.net/docs/install
*Note that it is a self-hosted setup.*
You then create an application and get a token, which is the `ApplicationToken`.
To send a notification, just use curl: https://gotify.net/docs/pushmsg

You can receive notifications on your browser or Android if you install the application.

I sent you an e-mail for you to test quickly this feature.

**Comment by tidusjar** [comment]
All tested and reviewed.

Excellent work! Everything works as expected and you have stuck to the same notification pattern. Nice job, Merging into develop

**Pull request merged**
