### PR TITLE
Add linting and indexes for interfaces/services

### PR DESCRIPTION
**Pull request by MattJeanes**

### CODE REVIEW

**Comment by tidusjar** [comment]
👎

**Comment by MattJeanes** [comment]
🖕

**Comment by MattJeanes** [comment]
Good to merge, recommend sooner than later before we get more conflicts..

**Comment by MattJeanes** [comment]
Linting works in VS2017, VSCode also but need to open the project folder instead of whole solution

**Comment by tidusjar** [comment]
Thanks sasuages king! I owe you one!

**Comment by MattJeanes** [comment]
I'll hold you to that :smirk:

**Pull request merged**
