### PR TITLE
fixed mobile newsletter.

### PR DESCRIPTION
**Pull request by d1slact0r**
Still this could use a lot of tidy up. Fixes: https://github.com/tidusjar/Ombi/issues/2431

### CODE REVIEW

**Comment by tidusjar** [comment]
Thanks a lot for this.

Do you mind posting some images on different devices before I merge?

**Comment by d1slact0r** [comment]
screenshot_20181108-215419
img-20181108-wa0027

**Comment by d1slact0r** [comment]
Just noticed that it looks a little different on iOS. Will test with Samsung tomorrow and will try and get iOS streamlined with Android as well.

**Comment by tidusjar** [comment]
OK cool! looks good so far

**Comment by tidusjar** [comment]
@anojht do you mind reviewing?

**Comment by anojht** [comment]
Thanks for this @d1slact0r if possible can you test the major email clients, I have tried to fix this in the past and when I accommodate for gmail, styles are broken on outlook and Samsung mail or other clients.

**Comment by d1slact0r** [comment]
Thanks for the compliments @anojht i had a busy weekend and will have a busy week as well. I do not have outlook but I have samsung. I will see what I can do right now.

**Comment by diedrichg** [comment]
@d1slact0r THANK YOU, THANK YOU, THANK YOU! It looks 1000% better! On Android Firefox I'm seeing the following issues:

1. Long descriptions get cut off and the genre is not shown
2. The "Powered by Ombi" is overlapping the bottom movie box.

Awesome job! Can't wait for the next fix!
screenshot_20181112-121824

**Comment by d1slact0r** [comment]
Pushed some extra commits. Can you guys test it? Here on android 8 it is working fine in the gmail app and also on ios 12. My samsung broke so can not test on that anymore :(

**Comment by anojht** [comment]
Just had a chance to test the new commits on the same clients as previous comment, the results are the same.

If it's just broken for gmail on 7.0 that is fine since Android has been updated anyways. However the styles are broken on outlook app for Android whereas it was working fine prior to the changes.

**Comment by diedrichg** [comment]
3981 is much worse than 3969
screenshot_20181118-174512

**Comment by d1slact0r** [comment]
Will have a look soon thanks for replying

**Comment by tidusjar** [comment]
Any progress on this?

**Comment by d1slact0r** [comment]
Not yet have been busy with work and we have holidays this week where I live so it is going a bit slow. probably this weekend.

**Comment by d1slact0r** [comment]
since this is a real mess I will open a new one since I have rewritten everything.

**Pull request closed without merging**
