### PR TITLE
Add new gif for V3 on README

### PR DESCRIPTION
**Pull request by jj-owens**

### CODE REVIEW

**Comment by tidusjar** [comment]
Can you download the latest build and redo it in English? Looks like you got a build with some missing translations too.

Can we do this flow:
Landing Page > Login > Search and Request > Show Requests?

**Comment by jj-owens** [comment]
Sure, absolutely! I'll get right on it. :)

**Comment by jj-owens** [comment]
How does this look?

https://imgur.com/Tn9KEZy

**Comment by tidusjar** [comment]
Sorry to ask again, but I've changed how the search and requests pages look, can we do this again and include the landing page?

Thanks!

**Comment by jj-owens** [comment]
Sure, I should be able to re-do this today!

**Pull request closed without merging**
