### PR TITLE
fix the UI a little

### PR DESCRIPTION
**Pull request by goldenpipes**
by moving the id="removeBtn" from the form tag to the button itself.

### CODE REVIEW

**Comment by tidusjar** [comment]
What's the purpose of this?

**Comment by goldenpipes** [comment]
current: 
https://i.imgur.com/9Ml8UkT.png

with fix: 
https://i.imgur.com/UoUAjVW.png

this allows us to use float right on the buttons to align them to the right side of the container which is a lot neater then just aligning them with a `left: 75%;`

**Comment by goldenpipes** [comment]
nothing calls that form with that specific id: right? that id is used elsewhere on buttons on the TV requests page. but not on the form. just on the button.

**Comment by tidusjar** [comment]
Ok cool!

**Pull request merged**
