### PR TITLE
Better dutch translation

### PR DESCRIPTION
**Pull request by PotatoQuality**
Working on better dutch translation not finished yet

### CODE REVIEW

**Comment by tidusjar** [comment]
Awesome!

Let me know when you have finished and i'll merge it into dev for you to take a look at :D

(Once you have changed the target branch from `master` to `dev` 😉  )

**Comment by SuperPotatoMen** [comment]
ehm whoops

**Comment by tidusjar** [comment]
There are conflicts since I changed all the translations to support Emby.

**Comment by tidusjar** [comment]
Please check my change to make sure that makes sense https://github.com/tidusjar/Ombi/pull/1283/commits/15385cfb4c1e621f7deab9c821bb563db98c7858

**Pull request closed without merging**
