### PR TITLE
Implement Basic Mass Email Functionality

### PR DESCRIPTION
**Pull request by dhruvb14**
Hey @tidusjar 
So this was my first stab and navigating around your codebase but I have gotten mass email working. It is currently rendered on Newletter tab in admin section. I plan on breaking it out when I add the features you mentioned for selective emailing of users. I have been working from a small 12" laptop screen since I travel during the week for work so I'll get to working on the additional features once home with more monitors. Just wanted to get what I had done out. I know the code's not the cleanest but NancyFX was kicking my but as i'm used to WebApi2.

Open feature request: #358

### CODE REVIEW

**Comment by dhruvb14** [comment]
Also missing some unit tests, but that'll be done once I get all the other wanted features in...

**Comment by SuperPotatoMen** [comment]
@dhruvb14 first of all, great work! Very nice that you like to help making features for Ombi.
i added a request to @tidusjar for a review the code.

**Comment by dhruvb14** [comment]
@SuperPotatoMen thanks! I was talking to @tidusjar about taking on more features soon as I'm using it for learning new tech. Angular 2x for entire UI will likely be my next move :-)

**Comment by tidusjar** [comment]
Excellent. I'll take a look tonight. I'm excited about the prospect of using angular!

**Comment by tidusjar** [comment]
Looks good dude! All Merged in!

**Pull request merged**
